### PR TITLE
Remove Trailing Whitespaces in JavaScript files

### PR DESCRIPTION
**Pull request by isairz**
Trailing space가 많아 보여서 지우는 패치를 작성해 보았습니다.
I hate trailing space.

### CODE REVIEW

**Comment by nakosung** [comment]
Thank you for PR. Please keep indentation untouched. 

https://sublimetext.userecho.com/topic/116114-only-trim-trailing-whitespace-on-lines-that-are-not-empty/

**Comment by nakosung** [comment]
bump

**Comment by isairz** [comment]
Sorry for late response. I was busy because NC SOFT interview :)

I don't thinks that article is a week reason to leave indentation in empty line.
See http://stackoverflow.com/questions/5917956/why-is-indentation-in-empty-lines-bad

**Comment by nakosung** [comment]
Good luck with you. By the way, your PR is stale now, please refresh it.

**Comment by isairz** [comment]
Updated.

**Comment by isairz** [comment]
Ping.

If you doesn't want to remove trailing spaces, I will just close PR.

**Comment by nakosung** [comment]
Currently unreal.js has no automated CI, please be sure that all examples run fine with your PR.

**Comment by isairz** [comment]
I used regular expression for this patch.
`:%s/\s+$//`

I believe this patch has no effect, but I will test all examples and inform the result.

**Comment by nakosung** [comment]
Thank you

**Comment by isairz** [comment]
I test all example and confirmed it works fine with my PR.
(Except HelloRest.js this cannot find localhost:3000)

hellounrealjs

**Comment by nakosung** [comment]
I really appreciate. :100:

**Comment by isairz** [comment]
Your welcome :)

**Pull request merged**
