### PR TITLE
Add Fetch API

### PR DESCRIPTION
**Pull request by isairz**
The Fetch API provides an interface for fetching resources (e.g., across
the network.) It will seem familiar to anyone who has used XMLHttpRequest,
but the new API provides a more powerful and flexible feature set.

This patch is a porting from whatwg-fetch (https://github.com/github/fetch)
that written as closely as possible to the standard Fetch specification at
https://fetch.spec.whatwg.org.

### CODE REVIEW

**Comment by isairz** [comment]
POST method is tested in my local test server.

I wanted to write example code using POST method, but I didn't find proper public api using that.

**Comment by nakosung** [comment]
try http://jsonplaceholder.typicode.com/. :)

**Comment by isairz** [comment]
It has bean delayed due to last final-exam and 2nd interview of ncsoft... sorry.
I will work this Saturday.

**Comment by nakosung** [comment]
been inactive for long time

**Pull request closed without merging**
