### PR TITLE
Adding android build support

### PR DESCRIPTION
**Pull request by marynate**
- Built with with android-ndk-r10d, gcc4.8

- Linked against v8-4.9.92 
(prebuilt v8 android library: https://github.com/marynate/Unreal.js/releases/download/v8-4.9.92-android/prebuilt-v8-4.9.92-Android-ARMv7-gcc4.8.zip)

### CODE REVIEW

**Comment by nakosung** [comment]
:100:

**Comment by nakosung** [comment]
Could you share build instruction? I'm upgrading V8 version upto 5.1.300.

**Comment by marynate** [comment]
Sure!

Here's my build process:

- replace 2 build file (build/standalone.gypi, tools/gyp/v8.gyp) with https://gist.github.com/marynate/311828d68fb9115a4f68c39e155282ee

- run "make android_arm.release -j4 i18nsupport=off snapshot=off" for armv7, and "make android_arm64.release -j4 i18nsupport=off snapshot=off" for arm64

And prebuilt libraries ( Not tested yet ) here:

- Prebuilt armv7 and arm64 libries with android-ndk-r10d, gcc4.8 (https://github.com/marynate/Unreal.js/releases/download/v8-5.1.300-android/prebuilt-v8-5.1.300-Android-ARMv7-ARM64-gcc4.8.zip)

**Comment by nakosung** [comment]
Oh, great to have prebuilt binaries! Thanks!

**Comment by marynate** [comment]
> Could you post build instructions for Linux on Wiki?

Done!

**Comment by nakosung** [comment]
I really appreciate your contribution! :)

**Pull request merged**
